export const REGIONS = {
  gom: {
    id: 'gom',
    name: 'Gulf of Mexico',
    shortName: 'GOM',
    center: [27.5, -90.5],
    zoom: 6,
    bounds: [[24, -98], [31, -82]],
    stormBasins: ['atlantic', 'epac'],
    timezone: 'America/Chicago',
  },
  northsea: {
    id: 'northsea',
    name: 'North Sea',
    shortName: 'NS',
    center: [58, 2],
    zoom: 5,
    bounds: [[51, -5], [62, 10]],
    stormBasins: [],
    timezone: 'Europe/London',
  },
  seasia: {
    id: 'seasia',
    name: 'Southeast Asia',
    shortName: 'SEA',
    center: [5, 110],
    zoom: 5,
    bounds: [[-5, 95], [15, 125]],
    stormBasins: ['wpac'],
    timezone: 'Asia/Singapore',
  },
  brazil: {
    id: 'brazil',
    name: 'Brazil Pre-salt',
    shortName: 'BRZ',
    center: [-24, -42],
    zoom: 6,
    bounds: [[-28, -50], [-20, -35]],
    stormBasins: [],
    timezone: 'America/Sao_Paulo',
  },
  westafrica: {
    id: 'westafrica',
    name: 'West Africa',
    shortName: 'WAF',
    center: [4, 4],
    zoom: 6,
    bounds: [[-5, -5], [10, 15]],
    stormBasins: [],
    timezone: 'Africa/Lagos',
  },
  australia: {
    id: 'australia',
    name: 'Australia',
    shortName: 'AUS',
    center: [-25, 125],
    zoom: 4,
    bounds: [[-45, 110], [-10, 155]],
    stormBasins: ['aus'],
    timezone: 'Australia/Perth',
  },
  middleeast: {
    id: 'middleeast',
    name: 'Middle East',
    shortName: 'ME',
    center: [26, 52],
    zoom: 6,
    bounds: [[22, 48], [32, 58]],
    stormBasins: ['nio'],
    timezone: 'Asia/Dubai',
  },
};

export const getRegionById = (id) => REGIONS[id] || null;
export const getRegionList = () => Object.values(REGIONS);
